자바스크립트는 비동기 처리를 위한 패턴으로 콜백함수를 사용하지만 가독성이 나쁘고 에러 처리가 곤란하며 여러 개의 비동기 처리를 한번에 처리하는 데도 한계가 있다.

ES6에서는 비동기 처리를 위해 프로미스를 도입했다.

프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 **비동기 처리 시점을 명확하게 표현**할 수 있다는 장점이 있다.

### 1. 비동기 처리를 위한 콜백 패턴의 단점

### 1-1 콜백 헬
**비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.**

따라서 **비동기 함수의 처리 결과(서버 응답)**에 대한 **후속 처리는 비동기 함수 내부에서 수행**해야 한다.
```jsx
get('/step1', a => {
    get(`/step2/${a}`, b => {
        get(`/step3/${b}`, c => {
            get(`/step4/${c}`, d => {
                console.log(d);
            });
        });
    });
});
```


### 1-2 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 문제점 중 가장 심각한 것은 에러 처리가 곤란하다는 것이다.
```jsx
try {
    setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
    // 에러를 캐치하지 못한다
    console.error('캐치한 에러', e);
}
```

**에러는 호출자 방향으로 전파**된다. 

즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 

하지만 `setTimeout`함수의 콜백 함수를 호출한 것은 `setTimeout`가 아니기 때문에 `catch`블록에서 캐치되지 않는다.

이러한 에러 처리가 곤란한 문제를 극복하기 위해 ES6에서 프로미스가 도입되었다.


### 2. 프로미스의 생성

Promise생성자 함수는 new 연산자와 함께 호출하면 프로미스를 생성한다. 이는 호스트 객체가 아닌 ECMAScript사양에 정의된 표준 빌트인 객체다.

Promise생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 `resolve`와 `reject`함수를 인수로 전달받는다.

```jsx
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
    // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
    if (/* 비동기 처리 성공 */) {
        resolve('result');
    } else { /* 비동기 처리 실패 */
        reject('failure reason');
    }
});
```

- 비동기 처리 성공 : `resolve`함수를 호출해 프로미스를 fulfilled 상태로 변경한다.
- 비동기 처리 실패 : `reject`함수를 호출해 프로미스를 rejected 상태로 변경한다.

이처럼 **프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정**된다.


### 3. 프로미스의 후속 처리 메서드

프로미스의 **비동기 처리 상태가 변화**하면 **후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된**다. 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

### 3-1 Promise.prototype.then

`then`메서드는 두 개의 콜백 함수를 인수로 전달받는다.

- 첫 번째 콜백 함수는 프로미스가 fulfilled상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 **처리 결과**를 인수로 전달받는다.
- 두 번째 콜백 함수는 프로미스가 rejected상태가 되면 호출된다. 이때 콜백 함수는 에러를 인수로 전달받는다.

```jsx
// fulfilled
new Promise(resolve => resolve('fulfilled'))
    .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
    .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

### 3-2 Promise.prototype.catch

`catch`메서드는 한 개의 콜백 함수를 인수로 전달받는다. `catch`메서드의 콜백 함수는 프로미스가 **`rejected`상태인 경우만 호출**된다.

```jsx
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
    .catch(e => console.log(e)); // Error: rejected
```


### 3-3 Promise.prototype.finally

`finally`메서드는 한 개의 콜백 함수를 인수로 전달받는다. `finally`메서드의 콜백 함수는 프로미스의 **성공 또는 실패와 상관없이 무조건 한 번 호출**된다.

`finally`메서드는 프로미스 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.

```jsx
new Promise(() => { })
    .finally(() => console.log('finally')); // finally
```


### 4. 프로미스의 에러 처리

비동기 처리에서 발생한 에러는 `then`메서드의 두 번째 콜백 함수로 처리할 수 있다.

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
    res => console.log(res),
    err => console.error(err)
); // Error: 404
```

`catch`를 사용해 처리할 수도 있다.

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
    .then(res => console.log(res))
    .catch(err => console.error(err)); // Error: 404
```


### 5. 프로미스 체이닝

`then, catch, finally`후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다. 

이를 프로미스 체이닝이라 한다.

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다. 

다만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.

콜백 패턴은 가독성이 좋지 않다. 

이 문제는 ES8에서 도입된 `async/await`를 통해 해결할 수 있다. 

`async/await`를 사용하면 후속 처리 메서드 없이 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

```jsx
async function fetchData() {
try {
	const response = await fetch('https://api.example.com/data');
	const data = await response.json();
	console.log(data);
} catch (error) {
		console.error('Error fetching data:', error);
	}
}
fetchData();
```



### 6. 프로미스의 정적 메서드

### 6-1 Promise.resolve/Promise.reject

`Promise.resolve/Promise.reject` 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

`Promise.resolve`메서드는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]
```

`Promise.reject` 메서드는 인수로 전달받은 값을 reject 하는 프로미스를 생성한다.

```jsx
// 에러 객체를 reject하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error('Error!'));
rejectedPromise.catch(console.log); // Error: Error!

const rejectedPromise = new Promise((_, reject) => reject(new Error('Error!')));
```


### 6-2 Promise.all

`Promise.all`메서드는 **여러 개의 비동기 처리를 모두 병렬 처리할 때 사용**한다.

이때 프로미스들이 모두 fulfilled상태가 되면 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다. 하나라도 완료가 되지 않았다면 나머지 완료된 함수들은 완료되지 않은 함수를 기다린다.

이 배열은 첫 번째 `then`메서드에 인수로 전달된다.

```jsx
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1()
    .then(data => {
        res.push(data);
        return requestData2();
    })
    .then(data => {
        res.push(data);
        return requestData3();
    })
    .then(data => {
        res.push(data);
        console.log(res); // [1, 2, 3] ⇒ 약 6초 소요
    })
    .catch(console.error);
```

```jsx
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
    .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
    .catch(console.error);
```


### 6-3 Promise.race

`Promise.race`메서드는  `Promise.all`과 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 이때 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 **가장 먼저 fulfilled상태**가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 **반환**한다.

```jsx
Promise.race([
    new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
    new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
    new Promise(resolve => setTimeout(() => resolve(3), 1000)) // 3
])
    .then(console.log) // 3
    .catch(console.log);
```

`Promise.race`메서드에 전달된 프로미스가 하나라도 rejected 상태가 되면 에러를 reject하는 새로운 프로미스를 즉시 반환한다.


### 7. 마이크로태스크 큐

프로미스 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장된다.

마이크로태스크 큐는 태스크 큐와 별도의 큐다.

마이크로태스크 큐는 태스크 큐보다 우선순위가 높다. 

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
    .then(() => console.log(2))
    .then(() => console.log(3));
```

따라서 위의 코드 출력은 1→2→3이 아닌 2→3→1이 된다.


### 8. fetch

`fetch`함수는 XMLHttpRequest객체와 마찬가지로 **HTTP요청 전송 기능을 제공**하는 클라이언 사이드 Web API다. 

`fetch`함수는 XMLHttpRequest보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

`fetch`함수에 HTTP요청을 전송할 URL과 HTTP요청 메서드, 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

`const promise  = fetch(url, [, options])`

**fetch함수는 HTTP응답을 나타내는 Reponse 객체를 래핑한 Promise객체를 반환**한다.

```jsx
fetch('https://jsonplaceholder.typicode.com/todos/1')
    .then(response => console.log(response));
```


`fetch`함수를 사용할 때는 에러 처리에 주의해야 한다.

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
    .then(() => console.log('ok'))
    .catch(() => console.log('error'));
```

에러가 출력될 것처럼 보이지만 ‘ok’ 가 출력된다.

fetch 함수가 반환하는 프로미스는 기본적으로 **404 Not Found나 500 Internal Server Error같은 HTTP에러가 발생해도 에러를 reject하지 않고** 불리언 타입의 ok상태를 false로 설정한 Response 객체를 resolve한다. 

오프라인 등의 **네트워크 장애나 CORS에러에 의해 요청이 완료되지 못한 경우에만 프로미스 reject**한다.

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
    // response는 HTTP 응답을 나타내는 Response 객체다.
    .then(response => {
        if (!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todo => console.log(todo))
    .catch(err => console.error(err));
```